---
version: "{build}"

install:
- cmd: git clone --depth 3 https://github.com/kit-data-manager/service-base.git

build_script:
- cmd: ./gradlew.bat check --no-daemon

shallow_clone: true

cache:
  - '%USERPROFILE%\.gradle'

notifications:
- provider: Email
  to:
  - thomas.jejkal@kit.edu
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true